/elevation_mapping_node:
  ros__parameters:
    subscribers:
      front_cam:
        topic_name: '/zed/zed_node/point_cloud/cloud_registered'
        data_type: pointcloud

    publishers:
      elevation_map_raw:
        layers: ['elevation']
        basic_layers: ['elevation']
        fps: 10.0
      elevation_map_filter:
        layers: ['inpaint']
        basic_layers: ['inpaint']
        fps: 5.0
